# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45f97e4c537c06ece6d6c4724589125a7bd6432ef9c38f3106ab98106504625607c36d191ef3f751bd69c4506e656fc9b73be6d080254f2e8106f1449d8eb364

test:
  secret_key_base: 7d8553d55ebcc21b3e06a41ad166b67135b00d234337ebc75f31aedbb127c152773f020107656c216eba483be87b33b761a8993bbfaf4cb38bc400260b33d093

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
